config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
  @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path, notice: "you add a task successfully"
    else
      render "new"
    end
  end

  private

  def task_params
    params.require(:task).permit(:title,
                                 :description,
                                 :priority,
                                 :status,
                                 :finish_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskApplication
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/tasks/_form.html.haml
%table
  %tr
    %td f.text_field :title 

app/views/tasks/index.html.haml
-# :javascript
-#   -# console.log("出力できているよ");


%h1 タスク一覧表
%table
  %thead
    %tr
      %th タスク名
      %th 優先度
      %th 終了予定日
  - @tasks.each do |task|
    %tbody
      %tr
        %td= link_to task.title, task_path(task)
        %td= task.priority
        %td= task.finish_at

= link_to "新規作成", new_task_path

app/views/tasks/new.html.haml
%h1 create a new task
= simple_form_for @task do |f|
  = f.input :title
  = f.input :description
  = f.input :priority
  = f.input :status, collection: ["未着手", "着手", "完了"]
  = f.input :finish_at
  = f.button :submit

app/views/tasks/show.html.haml
%h1 this is show page.